# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - StevenVanCourt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Use npm ci for faster, reliable builds
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present

      # Zip the necessary files and folders
      - name: Zip the application
        run: |
          zip -r my-app.zip src/ public/ package.json package-lock.json web.config

      - name: Upload zipped artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: zipped-app
          path: my-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download zipped artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: zipped-app

      # Unzip the application
      - name: Unzip the application
        run: unzip my-app.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'StevenVanCourt'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4C71EDC52D5F47249A3994F57D7BBCB9 }}
          package: .
          # Remove the startup-command if it's causing issues on a Windows web app
